### ISSUE TITLE
"files" field in package.json doesn't work properly in new node

### ISSUE THREAD

**Issue by JLarky** [bluwy/create-vite-extra#30]
I think `template-*` pattern doesn't work in new node anymore. I got the best results by just removing "files" section, but that causes `.*` files to be added in the root, which isn't probably that big of a problem. You can see on the screenshot that only README is getting sent from the template

<img width="890" alt="image" src="https://user-images.githubusercontent.com/7026/235038073-1c64adb9-3e22-4fbd-b7c2-ae0a82b61ae1.png">

**Comment by bluwy** [comment]
Seems like a breaking change from https://github.com/npm/npm-packlist, changing it to `template-*/**` fixes it, but causes npm v8 and pnpm to hang (because they're using an older version of `npm-packlist`). For now since I'm using pnpm to publish, I'm sticking with the current syntax for now. Thanks for bringing this up!
