### ISSUE TITLE
Improve react SSR render to `renderToPipeableStream`

### ISSUE THREAD

**Issue by Ibadichan** [bluwy/create-vite-extra#51]
Using current react ssr template lazy loading does not work because `renderToString` does not support `Suspense` on server.
We can use `renderToPipeableStream` and listen for `onAllReady` callback to "simulate"  `renderToString` behavior.

https://github.com/bluwy/create-vite-extra/pull/50

**Comment by bluwy** [comment]
Thanks for opening a PR. I'm not able to do a proper review to test it locally as I'll be away for the next week, but I'll make sure to do so when I return.

From a glance, I think I'd prefer adding a streaming specific template like https://github.com/bluwy/create-vite-extra/pull/46 (for Vue), so that users can choose between both. Ideally the code pattern should look as close as possible to that PR so that the templates are consistent.

**Comment by Ibadichan** [comment]
Ok, i will try to create similar template, thanks.

**Comment by Ibadichan** [comment]
Hi @bluwy, 
Please take a look & review this new PR
https://github.com/bluwy/create-vite-extra/pull/54.
