### ISSUE TITLE
Does the React SSR template support generating preload directives?

### ISSUE THREAD

**Issue by foucdeg** [bluwy/create-vite-extra#53]
In vite's SSR documentation, the [Generating Preload Directives section](https://vitejs.dev/guide/ssr#generating-preload-directives) section says:

> To leverage the manifest, frameworks need to provide a way to collect the module IDs of the components that were used during a server render call.

In the React template, the `ssrManifest` [variable](https://github.com/bluwy/create-vite-extra/blob/master/template-ssr-react/server.js#L13) seems to exist for that purpose, it is passed to the [render function](https://github.com/bluwy/create-vite-extra/blob/master/template-ssr-react/src/entry-server.jsx#L5), but the argument is never used.

Is there a working implementation available?

**Comment by Ibadichan** [comment]
> Generating Preload Directives section

Hi! Advice from developer, not maintainer) If you need to preload images/fonts you can use `react-helmet-async` library. What you need to achieve?

**Comment by bluwy** [comment]
The [Generating Preload Directives section](https://vitejs.dev/guide/ssr#generating-preload-directives) you linked also links to an example implementation for Vue. You should be able to mimic that and pass it down [to the server](https://github.com/vitejs/vite-plugin-vue/blob/fff40f67f05763d24e8c752fa98bcd08e19f7c82/playground/ssr-vue/server.js#L85-L89) in an agnostic way. At the moment, I'd like to keep the templates simple and because preloading can be business-logic-related.

@Ibadichan's advice may be helpful too.
